program: train.py
method: grid
metric:
  name: val_acc
  goal: maximize
parameters:
  activation:
    values: ['sigmoid', 'relu','tanh', 'silu', 'gelu', 'leaky_relu']
  optimizer:
    values: ['sgd', 'nesterov_sgd', 'adam', 'adagrad', 'rmsprop', 'adamw', 'adamax', 'nadam']
  lr:
    values: [0.01,0.001]
  batch_size:
    values: [64,256,512]
  epochs:
    values: [100,200]